version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala:
  - 2.11.12
  - 2.12.15
  - 2.13.6
  - 3.0.2

env:
  - SCALAJS_VERSION=          ADOPTOPENJDK=8
  - SCALAJS_VERSION=1.7.0     ADOPTOPENJDK=8
  - SCALANATIVE_VERSION=0.4.0 ADOPTOPENJDK=8
  - SCALAJS_VERSION=          ADOPTOPENJDK=11
  - SCALAJS_VERSION=          ADOPTOPENJDK=17

matrix:

  include:

    # run migration test
    - scala: 2.12.15
      env: TEST_SCALAFIX=true      ADOPTOPENJDK=8

    # run binary compatibility test
    - scala: 2.12.15
      env: TEST_BINARY_COMPAT=true ADOPTOPENJDK=8

    # run scalafmt
    - scala: 2.12.15
      env: TEST_SCALAFMT=true      ADOPTOPENJDK=8

  exclude:

    # Scala Native doesn't support Scala 3 yet

    - scala: 3.0.2
      env: SCALANATIVE_VERSION=0.4.0 ADOPTOPENJDK=8

install:
  - git fetch --tags # get all tags for sbt-dynver

script: sbt ci
