language: scala

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0

env:
  - SCALAJS_VERSION=         ADOPTOPENJDK=8
  - SCALAJS_VERSION=0.6.28   ADOPTOPENJDK=8
  - SCALAJS_VERSION=1.0.0-M8 ADOPTOPENJDK=8
  - SCALAJS_VERSION=         ADOPTOPENJDK=11
  - SCALAJS_VERSION=0.6.28   ADOPTOPENJDK=11
  - SCALAJS_VERSION=1.0.0-M8 ADOPTOPENJDK=11

matrix:

  include:

    # run migration test
    - scala: 2.12.8
      env: TEST_SCALAFIX=true           ADOPTOPENJDK=11

    # run binary compatibility test
    - scala: 2.12.8
      env: TEST_BINARY_COMPAT=true      ADOPTOPENJDK=11

    # run scalafmt
    - scala: 2.12.8
      env: TEST_SCALAFMT=true           ADOPTOPENJDK=11

    # Scala Native includes
    - scala: 2.11.12
      env: SCALANATIVE_VERSION=0.3.9    ADOPTOPENJDK=8

    - scala: 2.11.12
      env: SCALANATIVE_VERSION=0.4.0-M2 ADOPTOPENJDK=8

    - scala: 2.11.12
      env: SCALANATIVE_VERSION=0.3.9    ADOPTOPENJDK=11

    - scala: 2.11.12
      env: SCALANATIVE_VERSION=0.4.0-M2 ADOPTOPENJDK=11

before_install:
  # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
  - "[[ -d $HOME/.sdkman/bin ]] || rm -rf $HOME/.sdkman/"
  - curl -sL https://get.sdkman.io | bash
  - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"

install:
  - sdk install java $(sdk list java | grep -o "$ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1)
  - unset JAVA_HOME
  - java -Xmx32m -version
  - git fetch --tags # get all tags for sbt-dynver

before_script:
  - admin/checkCLA.sh

script: sbt ci

cache:
  directories:
    - "$HOME/.sbt/preloaded"
    - "$HOME/.sbt/1.0/dependency"
    - "$HOME/.sbt/boot/scala*"
    - "$HOME/.sbt/launchers"
    - "$HOME/.ivy2/cache"
    - "$HOME/.cache/coursier"
    - "$HOME/.sdkman"

before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- find $HOME/.ivy2/cache -name "*scalafix*.xml" -type f -delete
- rm -rf $HOME/.ivy2/local
