version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala:
  - 2.11.12
  - 2.12.12
  - 2.13.3
  - 3.0.0-M2
  - 3.0.0-M3

env:
  - SCALAJS_VERSION=       ADOPTOPENJDK=8
  - SCALAJS_VERSION=1.3.1  ADOPTOPENJDK=8
  - SCALAJS_VERSION=       ADOPTOPENJDK=11
  - SCALAJS_VERSION=1.3.1  ADOPTOPENJDK=11

matrix:

  include:

    # run migration test
    - scala: 2.12.12
      env: TEST_SCALAFIX=true           ADOPTOPENJDK=8

    # run binary compatibility test
    - scala: 2.12.12
      env: TEST_BINARY_COMPAT=true      ADOPTOPENJDK=8

    # run scalafmt
    - scala: 2.12.12
      env: TEST_SCALAFMT=true           ADOPTOPENJDK=8

    # Scala Native includes
    - scala: 2.11.12
      env: SCALANATIVE_VERSION=0.3.9    ADOPTOPENJDK=8

    - scala: 2.11.12
      env: SCALANATIVE_VERSION=0.4.0-M2 ADOPTOPENJDK=8

    - scala: 2.11.12
      env: SCALANATIVE_VERSION=0.3.9    ADOPTOPENJDK=11

    - scala: 2.11.12
      env: SCALANATIVE_VERSION=0.4.0-M2 ADOPTOPENJDK=11

install:
  - git fetch --tags # get all tags for sbt-dynver

before_script:
  - admin/checkCLA.sh

script: sbt ci
