# Needed for openjdk6
dist: precise
addons:
  hosts:
    - localhost
  hostname: localhost.local

language: scala

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0-M5
jdk:
  - openjdk6
  - oraclejdk8
env:
  global:

    # PGP_PASSPHRASE
    - secure: "rjetmX9HXoN/scxTCBFCHIUDFryY0Yd29sR6EBrW/2tCOILO09RTCcJB0kPn2YMZ9en8ChTtOpqGF9133f6wZ7/ZINSUt1tNwnbgDlhGbwJW2WFTUEmL7ScdqmgRGa294aVuAfrvJnr+dN92it6ibAB8nThgsjq0LnZREJsKwQ77vvEeATEKutuPLGlrHrmqL7/XCjb2uYz9Xh0sSpyQlKOGt5EN7JzM/Bzyju+RYS9BvnLVV86fey/UWO1DNDa4MU5835akevqvtwN7CpCFxFKgbfc+40bAh7Xc59UnkxP+Lcs2KxJx9heS6RJJiNEx99r59LL2JALyN++yOAS97HEfii4Yc3OK9VRZCNQFW4gNm3VtGNW4EC+LOX/9cUiUNg2J65nY0UF2d6R3vsqiCKaK6C0cm+jIs3fgDHFlB+MiHC/ZECaoPvwzm1AxQMIWyoFFqXuHQk3Ef137G0x1ejneUoGD/PqMbiEAX64+VVvOxgOI2/jyt4hFTEk6JiWVahmk+7oFAsLH1n9J1Y3csMvmo9S0S/Ey9D3bR07hggc8pj/CJPj9gFSfpGEVhroc37T/VlP23EVJgpteovERyeJGC3P7wVWvi1pNNW6iOVENzY1GkHlHkJUI7Q4B+eIW2mh5wi6JyC/DM2lO4z3M2KQkNqQgzIBdm5p/4hezkkA="
    # SONA_USER
    - secure: "oStf8s+LwXcmVENMnWU970OAImwXLV2E6FNXSLE7zdr4YL70cWVsDXDeAs0LSEmiOXTtHulmcIwUt6fCqZ1aiTxUxGX2avy0DSM9nCrQit7IXfwX8V9iK9/3t/SXo1g8yEfxyug+OK6CKOlLeA9HY/TJjO6fkYCsR1NrD8PLpgGtgSwS1GGjifbdahkQyyyivxROJ2UaRysm8PJ1X1966FoQoXKLU4HEztO48y3ZIlItZGwVv/1FJ18AniU2oCnV6XQVM+OB/j+IxNENzLBvd54/YjVtRRa22KTlC8j/NXo8Vq/f0ZhLjNLzYIEB1ER+2T2dthpek+Y8eMR5RdHrFj4Xp2kB04K70ZIL6pw2BDpqeiabjm1E3X6c+flj4pWR5p8uXguV7JmhYgl9d2UEqP7ZTzSbgh2S2WG9EjyK4C2L9jimgBP+Nih2yeW8GuURKgjQ5zrg3+7vxXqBjNN4PmTLpGiQ5shK1kZCpzdgfTl3LfUO4Uitg2Vl8yFC3Z9d3Fo5oV84DhL20pMIx7CtIcMX4b5QHArbUyICYFOvuz+8qP67kTPLVoErNmKWjqpp64VarqfoVbbe4NwRgGuNSMPR1nHb1LjloXv1CiNs9AocvnTknhV1T9I4F4XWi/J6mEwUbVW7GppzqszO6cAgcPLbqp92U8I+rexPjiieCZ0="
    # SONA_PASS
    - secure: "m0Fw/eH7RXJJoBTfqV6CMd7kaIN2pRPnQPNXJGb546UjqYAlYTkfjvVrWpsgpisRBptI1FEHn24yGbgAHjIes/4un/O62K66I0BffL8PbdeHeNcDjSrTesKEqage2mQfGOiqccVsmkgiKeXNYL8tPZRmPQQ3XZ97mS1SXWlqAJSMW6HfNnvqW14Gdb/snR6I8lQ2o5tRnLerWPnI96pp+xjZca2lD4XDvH2wLJXXLmYY61e23ZYzZMepxBxhGa7js3YTYzCWNrOfBLjFJ5nwRxbjR0WMuz5z5Gdy715WtguKS4Fffd/GJHycLROBU9LCAQDMTxMFvqzFqVFpfq0BuTmmkXFXj+a7dO+ABG0RfoDfoMjn7pHwyHNCZyMMuR1HCjMkbGFwC+Zme2UAYNivtcsuWWeMuypwjyqjfFfNns4FHJ0SXFtC/6+OJkAuUdbEJKReYWKWEsP5SnCH/8PLlc+uUl3tjQkFLc1sOAyx9cTWyBErwuJXhgTrjT9AWvO+fvhcm8z/p5+aaF/U9GIrzPqziX4hGjzc/WC+rsFJSiBDlFQl7br+m8WWs7/wuXqPGXmhf0BNQViDi7fZndDHcY3p3T0An05d/IMKjCUrgLDlJi6VYs9XN7S8ay6MH+XTwIsJGSxtGjfEO4rHGIjtR2GRr8TqdNfnpsI3ucbia1Y="
  matrix:
    - SCALAJS_VERSION=
    - SCALAJS_VERSION=0.6.26
    - SCALAJS_VERSION=1.0.0-M6

matrix:
  exclude:
    # > 2.12 requires jdk8
    - jdk: openjdk6
      scala: 2.12.8

    - jdk: openjdk6
      scala: 2.13.0-M5

    # ?
    - jdk: oraclejdk8
      scala: 2.11.12

    # 2.13.0-M5 is not available in Scala.js 1.0.0-M6
    - scala: 2.13.0-M5
      env: SCALAJS_VERSION=1.0.0-M6
  include:

    # run migration test
    - jdk: oraclejdk8
      scala: 2.12.8
      env: TEST_SCALAFIX=true

    # run binary compatibility test
    - jdk: oraclejdk8
      scala: 2.12.8
      env: TEST_BINARY_COMPAT=true

    # run scalafmt
    - jdk: oraclejdk8
      scala: 2.12.8
      env: TEST_SCALAFMT=true

# | jdk         |   scala   | scala target | scala target version | scalafix test |
# | ----------- | --------- | ------------ | -------------------- |---------------|
# |    openjdk6 | 2.11.12   | jvm          |                      |               |
# |    openjdk6 | 2.11.12   | js           | 0.6.26               |               |
# |    openjdk6 | 2.11.12   | js           | 1.0.0-M6             |               |
# |  oraclejdk8 | 2.12.8    | jvm          |                      |               |
# |  oraclejdk8 | 2.12.8    | js           | 0.6.26               |               |
# |  oraclejdk8 | 2.12.8    | js           | 1.0.0-M6             |               |
# |  oraclejdk8 | 2.13.0-M5 | jvm          |                      |               |
# |  oraclejdk8 | 2.13.0-M5 | js           | 0.6.26               |               |
# |  oraclejdk8 | 2.12.8    | jvm          |                      |   true        |

before_script:
  - nvm install 8
  - nvm use 8
  - admin/checkCLA.sh

script:
  # work around https://github.com/travis-ci/travis-ci/issues/9713
  - if [[ $JAVA_HOME = *java-6* ]]; then jdk_switcher use openjdk6; fi
  - java -version
  - node -v
  - if [[ "$TRAVIS_JDK_VERSION" == "openjdk6" ]]; then SBTOPTS="-Dsbt.override.build.repos=true -Dsbt.repository.config=./.sbtrepos"; fi
  - sbt $SBTOPTS ci

cache:
  directories:
  - "$HOME/.sbt/preloaded"
  - "$HOME/.sbt/0.13/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"

before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- find $HOME/.ivy2/cache -name "*scalafix*.xml" -type f -delete
- rm -rf $HOME/.ivy2/local
